### ISSUE TITLE
Make it work for private instance of Github Enterprise

### ISSUE THREAD

**Issue by kennydee** [ryanflorence/github-plusone-extension#8]
Hi

This plugin is awesome and really usefull.
Is there any way to make it works on private Github Enterprise instance  ?

With something like this i think in the manifest : 
`"matches": ["https://github.com/*","https://*/*/pull/*","https://*/*/issues/*"]`

Our private instance is on a domaine like `https://github.<ourPrivateDomain>.fr`

Thanks for your work

**Comment by kennydee** [comment]
If u're ok with that, i can make a pull request.

**Comment by tikotzky** [comment]
the issue I see with that is that github is it wont work when navigating around your enterprise instance, reason being that github doesnt do a full page refresh between pages. 

What that means is that the plugin will only load if you click on a link to an issue or PR if you browse to an issue or PR the plugin wont load...

**Comment by kennydee** [comment]
Oh you're right :(
The problem is the match pattern requirement for Chrome Extension as seen in https://developer.chrome.com/extensions/match_patterns ...
It seems to be impossible to do something like `https://*github.*` unfortunately :(

Any other idea to make this extension work for Github enterprise usage ?

Thanks again

**Comment by leereilly** [comment]
:bulb:You might get some ideas if you look at some of the PRs/commits referenced in https://github.com/buunguyen/octotree/pull/47 (another great Chrome extension). That works great with GitHub Enterprise:sparkles:

**Comment by kennydee** [comment]
Thanks to your link @leereilly, i have submit this #9 Pull Request fixing that.
